#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 110
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 80
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 14
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_func = 3,
  anon_sym_DASH_GT = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_EQ = 9,
  anon_sym_COMMA = 10,
  anon_sym_DOT = 11,
  anon_sym_f = 12,
  anon_sym_d = 13,
  anon_sym_true = 14,
  anon_sym_false = 15,
  sym_identifier = 16,
  sym__digits = 17,
  sym_semi = 18,
  sym_plus = 19,
  sym_minus = 20,
  sym_times = 21,
  sym_by = 22,
  sym_mod = 23,
  sym_lth = 24,
  sym_mth = 25,
  sym_eq = 26,
  sym_leq = 27,
  sym_meq = 28,
  sym_neq = 29,
  sym_or = 30,
  sym_and = 31,
  sym_source_file = 32,
  sym__definition = 33,
  sym__declaration = 34,
  sym__initialization = 35,
  sym__expression = 36,
  sym__par_expression = 37,
  sym__numbers = 38,
  sym__callable = 39,
  sym_declaration_statement = 40,
  sym_initialization_statement = 41,
  sym_function_definition = 42,
  sym_block = 43,
  sym_simple_declaration = 44,
  sym_array_declaration = 45,
  sym_simple_initialization = 46,
  sym_array_initialization = 47,
  sym_struct_initialization = 48,
  sym_struct_constructor_initialization = 49,
  sym_struct_list_initialization = 50,
  sym_initializer_list = 51,
  sym_parameters = 52,
  sym_arguments = 53,
  sym_arguments_list = 54,
  sym__binary_expression = 55,
  sym_add = 56,
  sym_substract = 57,
  sym_multiply = 58,
  sym_divide = 59,
  sym_mod_expr = 60,
  sym_lth_cmp = 61,
  sym_mth_cmp = 62,
  sym_eq_cmp = 63,
  sym_neq_cmp = 64,
  sym_leq_cmp = 65,
  sym_meq_cmp = 66,
  sym_and_expr = 67,
  sym_or_expr = 68,
  sym_array_access = 69,
  sym_attribute_access = 70,
  sym_function_call = 71,
  sym_int_literal = 72,
  sym_float_literal = 73,
  sym_double_literal = 74,
  sym_bool_literal = 75,
  aux_sym_source_file_repeat1 = 76,
  aux_sym_block_repeat1 = 77,
  aux_sym_parameters_repeat1 = 78,
  aux_sym_arguments_repeat1 = 79,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_func] = "func",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_f] = "f",
  [anon_sym_d] = "d",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_identifier] = "identifier",
  [sym__digits] = "_digits",
  [sym_semi] = "semi",
  [sym_plus] = "plus",
  [sym_minus] = "minus",
  [sym_times] = "times",
  [sym_by] = "by",
  [sym_mod] = "mod",
  [sym_lth] = "lth",
  [sym_mth] = "mth",
  [sym_eq] = "eq",
  [sym_leq] = "leq",
  [sym_meq] = "meq",
  [sym_neq] = "neq",
  [sym_or] = "or",
  [sym_and] = "and",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__declaration] = "_declaration",
  [sym__initialization] = "_initialization",
  [sym__expression] = "_expression",
  [sym__par_expression] = "_par_expression",
  [sym__numbers] = "_numbers",
  [sym__callable] = "_callable",
  [sym_declaration_statement] = "declaration_statement",
  [sym_initialization_statement] = "initialization_statement",
  [sym_function_definition] = "function_definition",
  [sym_block] = "block",
  [sym_simple_declaration] = "simple_declaration",
  [sym_array_declaration] = "array_declaration",
  [sym_simple_initialization] = "simple_initialization",
  [sym_array_initialization] = "array_initialization",
  [sym_struct_initialization] = "struct_initialization",
  [sym_struct_constructor_initialization] = "struct_constructor_initialization",
  [sym_struct_list_initialization] = "struct_list_initialization",
  [sym_initializer_list] = "initializer_list",
  [sym_parameters] = "parameters",
  [sym_arguments] = "arguments",
  [sym_arguments_list] = "arguments_list",
  [sym__binary_expression] = "_binary_expression",
  [sym_add] = "add",
  [sym_substract] = "substract",
  [sym_multiply] = "multiply",
  [sym_divide] = "divide",
  [sym_mod_expr] = "mod_expr",
  [sym_lth_cmp] = "lth_cmp",
  [sym_mth_cmp] = "mth_cmp",
  [sym_eq_cmp] = "eq_cmp",
  [sym_neq_cmp] = "neq_cmp",
  [sym_leq_cmp] = "leq_cmp",
  [sym_meq_cmp] = "meq_cmp",
  [sym_and_expr] = "and_expr",
  [sym_or_expr] = "or_expr",
  [sym_array_access] = "array_access",
  [sym_attribute_access] = "attribute_access",
  [sym_function_call] = "function_call",
  [sym_int_literal] = "int_literal",
  [sym_float_literal] = "float_literal",
  [sym_double_literal] = "double_literal",
  [sym_bool_literal] = "bool_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_f] = anon_sym_f,
  [anon_sym_d] = anon_sym_d,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_identifier] = sym_identifier,
  [sym__digits] = sym__digits,
  [sym_semi] = sym_semi,
  [sym_plus] = sym_plus,
  [sym_minus] = sym_minus,
  [sym_times] = sym_times,
  [sym_by] = sym_by,
  [sym_mod] = sym_mod,
  [sym_lth] = sym_lth,
  [sym_mth] = sym_mth,
  [sym_eq] = sym_eq,
  [sym_leq] = sym_leq,
  [sym_meq] = sym_meq,
  [sym_neq] = sym_neq,
  [sym_or] = sym_or,
  [sym_and] = sym_and,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__declaration] = sym__declaration,
  [sym__initialization] = sym__initialization,
  [sym__expression] = sym__expression,
  [sym__par_expression] = sym__par_expression,
  [sym__numbers] = sym__numbers,
  [sym__callable] = sym__callable,
  [sym_declaration_statement] = sym_declaration_statement,
  [sym_initialization_statement] = sym_initialization_statement,
  [sym_function_definition] = sym_function_definition,
  [sym_block] = sym_block,
  [sym_simple_declaration] = sym_simple_declaration,
  [sym_array_declaration] = sym_array_declaration,
  [sym_simple_initialization] = sym_simple_initialization,
  [sym_array_initialization] = sym_array_initialization,
  [sym_struct_initialization] = sym_struct_initialization,
  [sym_struct_constructor_initialization] = sym_struct_constructor_initialization,
  [sym_struct_list_initialization] = sym_struct_list_initialization,
  [sym_initializer_list] = sym_initializer_list,
  [sym_parameters] = sym_parameters,
  [sym_arguments] = sym_arguments,
  [sym_arguments_list] = sym_arguments_list,
  [sym__binary_expression] = sym__binary_expression,
  [sym_add] = sym_add,
  [sym_substract] = sym_substract,
  [sym_multiply] = sym_multiply,
  [sym_divide] = sym_divide,
  [sym_mod_expr] = sym_mod_expr,
  [sym_lth_cmp] = sym_lth_cmp,
  [sym_mth_cmp] = sym_mth_cmp,
  [sym_eq_cmp] = sym_eq_cmp,
  [sym_neq_cmp] = sym_neq_cmp,
  [sym_leq_cmp] = sym_leq_cmp,
  [sym_meq_cmp] = sym_meq_cmp,
  [sym_and_expr] = sym_and_expr,
  [sym_or_expr] = sym_or_expr,
  [sym_array_access] = sym_array_access,
  [sym_attribute_access] = sym_attribute_access,
  [sym_function_call] = sym_function_call,
  [sym_int_literal] = sym_int_literal,
  [sym_float_literal] = sym_float_literal,
  [sym_double_literal] = sym_double_literal,
  [sym_bool_literal] = sym_bool_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_d] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__digits] = {
    .visible = false,
    .named = true,
  },
  [sym_semi] = {
    .visible = true,
    .named = true,
  },
  [sym_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_minus] = {
    .visible = true,
    .named = true,
  },
  [sym_times] = {
    .visible = true,
    .named = true,
  },
  [sym_by] = {
    .visible = true,
    .named = true,
  },
  [sym_mod] = {
    .visible = true,
    .named = true,
  },
  [sym_lth] = {
    .visible = true,
    .named = true,
  },
  [sym_mth] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_leq] = {
    .visible = true,
    .named = true,
  },
  [sym_meq] = {
    .visible = true,
    .named = true,
  },
  [sym_neq] = {
    .visible = true,
    .named = true,
  },
  [sym_or] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym__initialization] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__par_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__numbers] = {
    .visible = false,
    .named = true,
  },
  [sym__callable] = {
    .visible = false,
    .named = true,
  },
  [sym_declaration_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_initialization_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_array_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_initialization] = {
    .visible = true,
    .named = true,
  },
  [sym_array_initialization] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_initialization] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_constructor_initialization] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_list_initialization] = {
    .visible = true,
    .named = true,
  },
  [sym_initializer_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments_list] = {
    .visible = true,
    .named = true,
  },
  [sym__binary_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_add] = {
    .visible = true,
    .named = true,
  },
  [sym_substract] = {
    .visible = true,
    .named = true,
  },
  [sym_multiply] = {
    .visible = true,
    .named = true,
  },
  [sym_divide] = {
    .visible = true,
    .named = true,
  },
  [sym_mod_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_lth_cmp] = {
    .visible = true,
    .named = true,
  },
  [sym_mth_cmp] = {
    .visible = true,
    .named = true,
  },
  [sym_eq_cmp] = {
    .visible = true,
    .named = true,
  },
  [sym_neq_cmp] = {
    .visible = true,
    .named = true,
  },
  [sym_leq_cmp] = {
    .visible = true,
    .named = true,
  },
  [sym_meq_cmp] = {
    .visible = true,
    .named = true,
  },
  [sym_and_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_or_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_array_access] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_access] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_int_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_double_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_attribute = 2,
  field_body = 3,
  field_function = 4,
  field_index = 5,
  field_lhs = 6,
  field_name = 7,
  field_parameters = 8,
  field_rhs = 9,
  field_size = 10,
  field_struct = 11,
  field_type = 12,
  field_value = 13,
  field_values = 14,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_attribute] = "attribute",
  [field_body] = "body",
  [field_function] = "function",
  [field_index] = "index",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_rhs] = "rhs",
  [field_size] = "size",
  [field_struct] = "struct",
  [field_type] = "type",
  [field_value] = "value",
  [field_values] = "values",
};

static const TSFieldMapSlice ts_field_map_slices[10] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 4},
  [9] = {.index = 15, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_type, 0},
  [2] =
    {field_values, 1},
  [3] =
    {field_value, 2},
  [4] =
    {field_arguments, 1},
    {field_function, 0},
  [6] =
    {field_size, 2},
  [7] =
    {field_attribute, 2},
    {field_struct, 0},
  [9] =
    {field_lhs, 0},
    {field_rhs, 2},
  [11] =
    {field_body, 5},
    {field_name, 1},
    {field_parameters, 2},
    {field_type, 4},
  [15] =
    {field_index, 2},
    {field_name, 0},
};

static TSSymbol ts_alias_sequences[10][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '%') ADVANCE(48);
      if (lookahead == '&') ADVANCE(2);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead == '+') ADVANCE(43);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '-') ADVANCE(45);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead == ';') ADVANCE(42);
      if (lookahead == '<') ADVANCE(49);
      if (lookahead == '=') ADVANCE(20);
      if (lookahead == '>') ADVANCE(50);
      if (lookahead == '[') ADVANCE(17);
      if (lookahead == ']') ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'c') ||
          lookahead == 'e' ||
          ('g' <= lookahead && lookahead <= 's') ||
          ('u' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 'd') ADVANCE(26);
      if (lookahead == 'f') ADVANCE(24);
      if (lookahead == 't') ADVANCE(34);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '|') ADVANCE(8);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '%') ADVANCE(48);
      if (lookahead == '&') ADVANCE(2);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead == '+') ADVANCE(43);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '-') ADVANCE(44);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead == ';') ADVANCE(42);
      if (lookahead == '<') ADVANCE(49);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '>') ADVANCE(50);
      if (lookahead == 'd') ADVANCE(25);
      if (lookahead == 'f') ADVANCE(23);
      if (lookahead == '|') ADVANCE(8);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '&') ADVANCE(56);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == ';') ADVANCE(42);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '[') ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'e') ||
          ('g' <= lookahead && lookahead <= 's') ||
          ('u' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 'f') ADVANCE(38);
      if (lookahead == 't') ADVANCE(34);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(54);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == '|') ADVANCE(55);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '%') ADVANCE(48);
      if (lookahead == '&') ADVANCE(2);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead == '+') ADVANCE(43);
      if (lookahead == ',') ADVANCE(21);
      if (lookahead == '-') ADVANCE(44);
      if (lookahead == '.') ADVANCE(22);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead == ';') ADVANCE(42);
      if (lookahead == '<') ADVANCE(49);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '>') ADVANCE(50);
      if (lookahead == '[') ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'e') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 'f') ADVANCE(36);
      if (lookahead == '|') ADVANCE(8);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_func);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_f);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_f);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 't') ||
          ('v' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 'a') ADVANCE(32);
      if (lookahead == 'u') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_d);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_d);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_true);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_false);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          lookahead == 'a' ||
          lookahead == 'b' ||
          ('d' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 'c') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'd') ||
          ('f' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 'e') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'd') ||
          ('f' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 'e') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'k') ||
          ('m' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 'l') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'm') ||
          ('o' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 'n') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'q') ||
          ('s' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 'r') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'r') ||
          ('t' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 's') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 't') ||
          ('v' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 'u') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 't') ||
          ('v' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 'u') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead == 'a') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__digits);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_semi);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_plus);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_minus);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_minus);
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_times);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_by);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_mod);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_lth);
      if (lookahead == '=') ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_mth);
      if (lookahead == '=') ADVANCE(53);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_leq);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_meq);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_neq);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_or);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_and);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 9},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 9},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 9},
  [40] = {.lex_state = 9},
  [41] = {.lex_state = 9},
  [42] = {.lex_state = 9},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 9},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 9},
  [49] = {.lex_state = 9},
  [50] = {.lex_state = 9},
  [51] = {.lex_state = 9},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 9},
  [54] = {.lex_state = 9},
  [55] = {.lex_state = 9},
  [56] = {.lex_state = 9},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 9},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 9},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 9},
  [73] = {.lex_state = 9},
  [74] = {.lex_state = 9},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 4},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 4},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 4},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 3},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 4},
  [102] = {.lex_state = 4},
  [103] = {.lex_state = 3},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_f] = ACTIONS(1),
    [anon_sym_d] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym__digits] = ACTIONS(1),
    [sym_semi] = ACTIONS(1),
    [sym_plus] = ACTIONS(1),
    [sym_minus] = ACTIONS(1),
    [sym_times] = ACTIONS(1),
    [sym_by] = ACTIONS(1),
    [sym_mod] = ACTIONS(1),
    [sym_lth] = ACTIONS(1),
    [sym_mth] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym_leq] = ACTIONS(1),
    [sym_meq] = ACTIONS(1),
    [sym_neq] = ACTIONS(1),
    [sym_or] = ACTIONS(1),
    [sym_and] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(93),
    [sym__definition] = STATE(28),
    [sym__declaration] = STATE(94),
    [sym__initialization] = STATE(96),
    [sym_declaration_statement] = STATE(28),
    [sym_initialization_statement] = STATE(28),
    [sym_function_definition] = STATE(28),
    [sym_simple_declaration] = STATE(62),
    [sym_array_declaration] = STATE(77),
    [sym_simple_initialization] = STATE(96),
    [sym_array_initialization] = STATE(96),
    [sym_struct_initialization] = STATE(96),
    [sym_struct_constructor_initialization] = STATE(98),
    [sym_struct_list_initialization] = STATE(98),
    [aux_sym_source_file_repeat1] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_func] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    STATE(88), 1,
      sym_arguments_list,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(53), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [54] = 10,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    STATE(105), 1,
      sym_initializer_list,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(56), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [108] = 9,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    ACTIONS(23), 1,
      anon_sym_RPAREN,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(54), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [159] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(39), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [207] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [255] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [303] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [351] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(51), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [399] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [447] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(44), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [495] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(47), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [543] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [591] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [639] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [687] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [735] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(52), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [783] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(42), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [831] = 8,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym__digits,
    STATE(24), 1,
      sym_attribute_access,
    STATE(85), 1,
      sym__callable,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(34), 23,
      sym__expression,
      sym__par_expression,
      sym__numbers,
      sym__binary_expression,
      sym_add,
      sym_substract,
      sym_multiply,
      sym_divide,
      sym_mod_expr,
      sym_lth_cmp,
      sym_mth_cmp,
      sym_eq_cmp,
      sym_neq_cmp,
      sym_leq_cmp,
      sym_meq_cmp,
      sym_and_expr,
      sym_or_expr,
      sym_array_access,
      sym_function_call,
      sym_int_literal,
      sym_float_literal,
      sym_double_literal,
      sym_bool_literal,
  [879] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      anon_sym_LBRACK,
    ACTIONS(31), 1,
      anon_sym_DOT,
    ACTIONS(33), 2,
      sym_lth,
      sym_mth,
    ACTIONS(27), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [910] = 4,
    ACTIONS(37), 1,
      anon_sym_f,
    ACTIONS(39), 1,
      anon_sym_d,
    ACTIONS(41), 2,
      sym_lth,
      sym_mth,
    ACTIONS(35), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [938] = 4,
    ACTIONS(45), 1,
      anon_sym_f,
    ACTIONS(47), 1,
      anon_sym_d,
    ACTIONS(49), 2,
      sym_lth,
      sym_mth,
    ACTIONS(43), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [966] = 3,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(55), 2,
      sym_lth,
      sym_mth,
    ACTIONS(51), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [991] = 3,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 2,
      sym_lth,
      sym_mth,
    ACTIONS(27), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1016] = 2,
    ACTIONS(59), 2,
      sym_lth,
      sym_mth,
    ACTIONS(57), 16,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1039] = 2,
    ACTIONS(63), 2,
      sym_lth,
      sym_mth,
    ACTIONS(61), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1061] = 2,
    ACTIONS(67), 2,
      sym_lth,
      sym_mth,
    ACTIONS(65), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1083] = 9,
    ACTIONS(5), 1,
      anon_sym_func,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    STATE(62), 1,
      sym_simple_declaration,
    STATE(77), 1,
      sym_array_declaration,
    STATE(94), 1,
      sym__declaration,
    STATE(98), 2,
      sym_struct_constructor_initialization,
      sym_struct_list_initialization,
    STATE(96), 4,
      sym__initialization,
      sym_simple_initialization,
      sym_array_initialization,
      sym_struct_initialization,
    STATE(45), 5,
      sym__definition,
      sym_declaration_statement,
      sym_initialization_statement,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1119] = 2,
    ACTIONS(73), 2,
      sym_lth,
      sym_mth,
    ACTIONS(71), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1141] = 2,
    ACTIONS(77), 2,
      sym_lth,
      sym_mth,
    ACTIONS(75), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1163] = 2,
    ACTIONS(81), 2,
      sym_lth,
      sym_mth,
    ACTIONS(79), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1185] = 6,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(85), 2,
      sym_lth,
      sym_mth,
    ACTIONS(83), 11,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_leq,
      sym_meq,
  [1215] = 6,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(97), 2,
      sym_lth,
      sym_mth,
    ACTIONS(95), 11,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_leq,
      sym_meq,
  [1245] = 3,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(101), 2,
      sym_lth,
      sym_mth,
    ACTIONS(99), 14,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_and,
  [1269] = 2,
    ACTIONS(105), 2,
      sym_lth,
      sym_mth,
    ACTIONS(103), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1291] = 4,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(109), 2,
      sym_lth,
      sym_mth,
    ACTIONS(107), 13,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
  [1317] = 2,
    ACTIONS(113), 2,
      sym_lth,
      sym_mth,
    ACTIONS(111), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1339] = 2,
    ACTIONS(117), 2,
      sym_lth,
      sym_mth,
    ACTIONS(115), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1361] = 4,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(121), 2,
      sym_lth,
      sym_mth,
    ACTIONS(119), 13,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
  [1387] = 2,
    ACTIONS(41), 2,
      sym_lth,
      sym_mth,
    ACTIONS(35), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1409] = 2,
    ACTIONS(125), 2,
      sym_lth,
      sym_mth,
    ACTIONS(123), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1431] = 2,
    ACTIONS(129), 2,
      sym_lth,
      sym_mth,
    ACTIONS(127), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1453] = 6,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(133), 2,
      sym_lth,
      sym_mth,
    ACTIONS(131), 11,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_leq,
      sym_meq,
  [1483] = 11,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(137), 1,
      sym_plus,
    ACTIONS(139), 1,
      sym_minus,
    ACTIONS(141), 1,
      sym_lth,
    ACTIONS(143), 1,
      sym_mth,
    ACTIONS(145), 1,
      sym_leq,
    ACTIONS(147), 1,
      sym_meq,
    ACTIONS(135), 7,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_times,
      sym_by,
      sym_mod,
  [1523] = 9,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    ACTIONS(151), 1,
      anon_sym_func,
    ACTIONS(154), 1,
      sym_identifier,
    STATE(62), 1,
      sym_simple_declaration,
    STATE(77), 1,
      sym_array_declaration,
    STATE(94), 1,
      sym__declaration,
    STATE(98), 2,
      sym_struct_constructor_initialization,
      sym_struct_list_initialization,
    STATE(96), 4,
      sym__initialization,
      sym_simple_initialization,
      sym_array_initialization,
      sym_struct_initialization,
    STATE(45), 5,
      sym__definition,
      sym_declaration_statement,
      sym_initialization_statement,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1559] = 2,
    ACTIONS(159), 2,
      sym_lth,
      sym_mth,
    ACTIONS(157), 15,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_eq,
      sym_leq,
      sym_meq,
      sym_neq,
      sym_or,
      sym_and,
  [1581] = 11,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(137), 1,
      sym_plus,
    ACTIONS(139), 1,
      sym_minus,
    ACTIONS(141), 1,
      sym_lth,
    ACTIONS(143), 1,
      sym_mth,
    ACTIONS(145), 1,
      sym_leq,
    ACTIONS(147), 1,
      sym_meq,
    ACTIONS(161), 7,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_times,
      sym_by,
      sym_mod,
  [1621] = 11,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(137), 1,
      sym_plus,
    ACTIONS(139), 1,
      sym_minus,
    ACTIONS(141), 1,
      sym_lth,
    ACTIONS(143), 1,
      sym_mth,
    ACTIONS(145), 1,
      sym_leq,
    ACTIONS(147), 1,
      sym_meq,
    ACTIONS(163), 7,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_times,
      sym_by,
      sym_mod,
  [1661] = 9,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(141), 1,
      sym_lth,
    ACTIONS(143), 1,
      sym_mth,
    ACTIONS(145), 1,
      sym_leq,
    ACTIONS(147), 1,
      sym_meq,
    ACTIONS(165), 9,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
  [1697] = 9,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(141), 1,
      sym_lth,
    ACTIONS(143), 1,
      sym_mth,
    ACTIONS(145), 1,
      sym_leq,
    ACTIONS(147), 1,
      sym_meq,
    ACTIONS(167), 9,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
  [1733] = 6,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(171), 2,
      sym_lth,
      sym_mth,
    ACTIONS(169), 11,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_semi,
      sym_plus,
      sym_minus,
      sym_times,
      sym_by,
      sym_mod,
      sym_leq,
      sym_meq,
  [1763] = 14,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(137), 1,
      sym_plus,
    ACTIONS(139), 1,
      sym_minus,
    ACTIONS(141), 1,
      sym_lth,
    ACTIONS(143), 1,
      sym_mth,
    ACTIONS(145), 1,
      sym_leq,
    ACTIONS(147), 1,
      sym_meq,
    ACTIONS(175), 1,
      sym_times,
    ACTIONS(177), 1,
      sym_by,
    ACTIONS(179), 1,
      sym_mod,
    ACTIONS(173), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1808] = 16,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(137), 1,
      sym_plus,
    ACTIONS(139), 1,
      sym_minus,
    ACTIONS(141), 1,
      sym_lth,
    ACTIONS(143), 1,
      sym_mth,
    ACTIONS(145), 1,
      sym_leq,
    ACTIONS(147), 1,
      sym_meq,
    ACTIONS(175), 1,
      sym_times,
    ACTIONS(177), 1,
      sym_by,
    ACTIONS(179), 1,
      sym_mod,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_arguments_repeat1,
  [1857] = 16,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(137), 1,
      sym_plus,
    ACTIONS(139), 1,
      sym_minus,
    ACTIONS(141), 1,
      sym_lth,
    ACTIONS(143), 1,
      sym_mth,
    ACTIONS(145), 1,
      sym_leq,
    ACTIONS(147), 1,
      sym_meq,
    ACTIONS(175), 1,
      sym_times,
    ACTIONS(177), 1,
      sym_by,
    ACTIONS(179), 1,
      sym_mod,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_arguments_repeat1,
  [1906] = 14,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(137), 1,
      sym_plus,
    ACTIONS(139), 1,
      sym_minus,
    ACTIONS(141), 1,
      sym_lth,
    ACTIONS(143), 1,
      sym_mth,
    ACTIONS(145), 1,
      sym_leq,
    ACTIONS(147), 1,
      sym_meq,
    ACTIONS(175), 1,
      sym_times,
    ACTIONS(177), 1,
      sym_by,
    ACTIONS(179), 1,
      sym_mod,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
  [1949] = 14,
    ACTIONS(87), 1,
      sym_eq,
    ACTIONS(89), 1,
      sym_neq,
    ACTIONS(91), 1,
      sym_or,
    ACTIONS(93), 1,
      sym_and,
    ACTIONS(137), 1,
      sym_plus,
    ACTIONS(139), 1,
      sym_minus,
    ACTIONS(141), 1,
      sym_lth,
    ACTIONS(143), 1,
      sym_mth,
    ACTIONS(145), 1,
      sym_leq,
    ACTIONS(147), 1,
      sym_meq,
    ACTIONS(175), 1,
      sym_times,
    ACTIONS(177), 1,
      sym_by,
    ACTIONS(179), 1,
      sym_mod,
    ACTIONS(189), 1,
      sym_semi,
  [1992] = 5,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(84), 1,
      sym_simple_declaration,
    STATE(58), 2,
      sym_declaration_statement,
      aux_sym_block_repeat1,
    STATE(109), 2,
      sym__declaration,
      sym_array_declaration,
  [2010] = 5,
    ACTIONS(193), 1,
      sym_identifier,
    ACTIONS(195), 1,
      anon_sym_RBRACE,
    STATE(84), 1,
      sym_simple_declaration,
    STATE(59), 2,
      sym_declaration_statement,
      aux_sym_block_repeat1,
    STATE(109), 2,
      sym__declaration,
      sym_array_declaration,
  [2028] = 5,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    ACTIONS(199), 1,
      sym_identifier,
    STATE(84), 1,
      sym_simple_declaration,
    STATE(59), 2,
      sym_declaration_statement,
      aux_sym_block_repeat1,
    STATE(109), 2,
      sym__declaration,
      sym_array_declaration,
  [2046] = 5,
    ACTIONS(193), 1,
      sym_identifier,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym_declaration_statement,
    STATE(84), 1,
      sym_simple_declaration,
    STATE(94), 2,
      sym__declaration,
      sym_array_declaration,
  [2063] = 2,
    ACTIONS(206), 2,
      anon_sym_func,
      sym_identifier,
    ACTIONS(204), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2073] = 5,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
    ACTIONS(210), 1,
      anon_sym_LBRACK,
    ACTIONS(212), 1,
      anon_sym_EQ,
    ACTIONS(214), 1,
      sym_semi,
    STATE(99), 1,
      sym_arguments,
  [2089] = 4,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(78), 1,
      sym_declaration_statement,
    STATE(84), 1,
      sym_simple_declaration,
    STATE(94), 2,
      sym__declaration,
      sym_array_declaration,
  [2103] = 1,
    ACTIONS(216), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_EQ,
      sym_semi,
  [2110] = 3,
    ACTIONS(218), 1,
      anon_sym_COMMA,
    STATE(65), 1,
      aux_sym_arguments_repeat1,
    ACTIONS(173), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [2121] = 3,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    STATE(68), 1,
      aux_sym_parameters_repeat1,
  [2131] = 3,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      aux_sym_arguments_repeat1,
  [2141] = 3,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_parameters_repeat1,
  [2151] = 3,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(229), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      aux_sym_arguments_repeat1,
  [2161] = 2,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
    ACTIONS(233), 2,
      anon_sym_func,
      sym_identifier,
  [2169] = 3,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
    ACTIONS(237), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_parameters_repeat1,
  [2179] = 2,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
    ACTIONS(242), 2,
      anon_sym_func,
      sym_identifier,
  [2187] = 2,
    ACTIONS(244), 1,
      ts_builtin_sym_end,
    ACTIONS(246), 2,
      anon_sym_func,
      sym_identifier,
  [2195] = 2,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
    ACTIONS(250), 2,
      anon_sym_func,
      sym_identifier,
  [2203] = 2,
    ACTIONS(252), 1,
      anon_sym_LBRACE,
    STATE(72), 1,
      sym_block,
  [2210] = 1,
    ACTIONS(254), 2,
      anon_sym_EQ,
      sym_semi,
  [2215] = 2,
    ACTIONS(214), 1,
      sym_semi,
    ACTIONS(256), 1,
      anon_sym_EQ,
  [2222] = 1,
    ACTIONS(235), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [2227] = 1,
    ACTIONS(204), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [2232] = 2,
    ACTIONS(258), 1,
      anon_sym_LPAREN,
    STATE(91), 1,
      sym_parameters,
  [2239] = 2,
    ACTIONS(260), 1,
      sym__digits,
    STATE(106), 1,
      sym_int_literal,
  [2246] = 2,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    STATE(104), 1,
      sym_initializer_list,
  [2253] = 2,
    ACTIONS(260), 1,
      sym__digits,
    STATE(87), 1,
      sym_int_literal,
  [2260] = 2,
    ACTIONS(210), 1,
      anon_sym_LBRACK,
    ACTIONS(214), 1,
      sym_semi,
  [2267] = 2,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
    STATE(35), 1,
      sym_arguments,
  [2274] = 1,
    ACTIONS(262), 1,
      sym_identifier,
  [2278] = 1,
    ACTIONS(264), 1,
      anon_sym_RBRACK,
  [2282] = 1,
    ACTIONS(266), 1,
      anon_sym_RBRACE,
  [2286] = 1,
    ACTIONS(268), 1,
      sym_identifier,
  [2290] = 1,
    ACTIONS(270), 1,
      anon_sym_DASH_GT,
  [2294] = 1,
    ACTIONS(272), 1,
      anon_sym_DASH_GT,
  [2298] = 1,
    ACTIONS(274), 1,
      sym_semi,
  [2302] = 1,
    ACTIONS(276), 1,
      ts_builtin_sym_end,
  [2306] = 1,
    ACTIONS(278), 1,
      sym_semi,
  [2310] = 1,
    ACTIONS(280), 1,
      sym_semi,
  [2314] = 1,
    ACTIONS(282), 1,
      sym_semi,
  [2318] = 1,
    ACTIONS(284), 1,
      anon_sym_DASH_GT,
  [2322] = 1,
    ACTIONS(286), 1,
      sym_semi,
  [2326] = 1,
    ACTIONS(288), 1,
      sym_semi,
  [2330] = 1,
    ACTIONS(290), 1,
      sym__digits,
  [2334] = 1,
    ACTIONS(292), 1,
      sym_identifier,
  [2338] = 1,
    ACTIONS(294), 1,
      sym_identifier,
  [2342] = 1,
    ACTIONS(296), 1,
      anon_sym_DASH_GT,
  [2346] = 1,
    ACTIONS(298), 1,
      sym_semi,
  [2350] = 1,
    ACTIONS(300), 1,
      sym_semi,
  [2354] = 1,
    ACTIONS(302), 1,
      anon_sym_RBRACK,
  [2358] = 1,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
  [2362] = 1,
    ACTIONS(304), 1,
      sym__digits,
  [2366] = 1,
    ACTIONS(306), 1,
      sym_semi,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 108,
  [SMALL_STATE(5)] = 159,
  [SMALL_STATE(6)] = 207,
  [SMALL_STATE(7)] = 255,
  [SMALL_STATE(8)] = 303,
  [SMALL_STATE(9)] = 351,
  [SMALL_STATE(10)] = 399,
  [SMALL_STATE(11)] = 447,
  [SMALL_STATE(12)] = 495,
  [SMALL_STATE(13)] = 543,
  [SMALL_STATE(14)] = 591,
  [SMALL_STATE(15)] = 639,
  [SMALL_STATE(16)] = 687,
  [SMALL_STATE(17)] = 735,
  [SMALL_STATE(18)] = 783,
  [SMALL_STATE(19)] = 831,
  [SMALL_STATE(20)] = 879,
  [SMALL_STATE(21)] = 910,
  [SMALL_STATE(22)] = 938,
  [SMALL_STATE(23)] = 966,
  [SMALL_STATE(24)] = 991,
  [SMALL_STATE(25)] = 1016,
  [SMALL_STATE(26)] = 1039,
  [SMALL_STATE(27)] = 1061,
  [SMALL_STATE(28)] = 1083,
  [SMALL_STATE(29)] = 1119,
  [SMALL_STATE(30)] = 1141,
  [SMALL_STATE(31)] = 1163,
  [SMALL_STATE(32)] = 1185,
  [SMALL_STATE(33)] = 1215,
  [SMALL_STATE(34)] = 1245,
  [SMALL_STATE(35)] = 1269,
  [SMALL_STATE(36)] = 1291,
  [SMALL_STATE(37)] = 1317,
  [SMALL_STATE(38)] = 1339,
  [SMALL_STATE(39)] = 1361,
  [SMALL_STATE(40)] = 1387,
  [SMALL_STATE(41)] = 1409,
  [SMALL_STATE(42)] = 1431,
  [SMALL_STATE(43)] = 1453,
  [SMALL_STATE(44)] = 1483,
  [SMALL_STATE(45)] = 1523,
  [SMALL_STATE(46)] = 1559,
  [SMALL_STATE(47)] = 1581,
  [SMALL_STATE(48)] = 1621,
  [SMALL_STATE(49)] = 1661,
  [SMALL_STATE(50)] = 1697,
  [SMALL_STATE(51)] = 1733,
  [SMALL_STATE(52)] = 1763,
  [SMALL_STATE(53)] = 1808,
  [SMALL_STATE(54)] = 1857,
  [SMALL_STATE(55)] = 1906,
  [SMALL_STATE(56)] = 1949,
  [SMALL_STATE(57)] = 1992,
  [SMALL_STATE(58)] = 2010,
  [SMALL_STATE(59)] = 2028,
  [SMALL_STATE(60)] = 2046,
  [SMALL_STATE(61)] = 2063,
  [SMALL_STATE(62)] = 2073,
  [SMALL_STATE(63)] = 2089,
  [SMALL_STATE(64)] = 2103,
  [SMALL_STATE(65)] = 2110,
  [SMALL_STATE(66)] = 2121,
  [SMALL_STATE(67)] = 2131,
  [SMALL_STATE(68)] = 2141,
  [SMALL_STATE(69)] = 2151,
  [SMALL_STATE(70)] = 2161,
  [SMALL_STATE(71)] = 2169,
  [SMALL_STATE(72)] = 2179,
  [SMALL_STATE(73)] = 2187,
  [SMALL_STATE(74)] = 2195,
  [SMALL_STATE(75)] = 2203,
  [SMALL_STATE(76)] = 2210,
  [SMALL_STATE(77)] = 2215,
  [SMALL_STATE(78)] = 2222,
  [SMALL_STATE(79)] = 2227,
  [SMALL_STATE(80)] = 2232,
  [SMALL_STATE(81)] = 2239,
  [SMALL_STATE(82)] = 2246,
  [SMALL_STATE(83)] = 2253,
  [SMALL_STATE(84)] = 2260,
  [SMALL_STATE(85)] = 2267,
  [SMALL_STATE(86)] = 2274,
  [SMALL_STATE(87)] = 2278,
  [SMALL_STATE(88)] = 2282,
  [SMALL_STATE(89)] = 2286,
  [SMALL_STATE(90)] = 2290,
  [SMALL_STATE(91)] = 2294,
  [SMALL_STATE(92)] = 2298,
  [SMALL_STATE(93)] = 2302,
  [SMALL_STATE(94)] = 2306,
  [SMALL_STATE(95)] = 2310,
  [SMALL_STATE(96)] = 2314,
  [SMALL_STATE(97)] = 2318,
  [SMALL_STATE(98)] = 2322,
  [SMALL_STATE(99)] = 2326,
  [SMALL_STATE(100)] = 2330,
  [SMALL_STATE(101)] = 2334,
  [SMALL_STATE(102)] = 2338,
  [SMALL_STATE(103)] = 2342,
  [SMALL_STATE(104)] = 2346,
  [SMALL_STATE(105)] = 2350,
  [SMALL_STATE(106)] = 2354,
  [SMALL_STATE(107)] = 2358,
  [SMALL_STATE(108)] = 2362,
  [SMALL_STATE(109)] = 2366,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__callable, 1),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_literal, 3),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_literal, 3),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_literal, 2),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_literal, 2),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int_literal, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int_literal, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_access, 3, .production_id = 6),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_access, 3, .production_id = 6),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_literal, 4),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float_literal, 4),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 4),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_literal, 3),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float_literal, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool_literal, 1),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool_literal, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__par_expression, 3),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__par_expression, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meq_cmp, 3, .production_id = 7),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_meq_cmp, 3, .production_id = 7),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_leq_cmp, 3, .production_id = 7),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_leq_cmp, 3, .production_id = 7),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_and_expr, 3, .production_id = 7),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_and_expr, 3, .production_id = 7),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, .production_id = 4),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2, .production_id = 4),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eq_cmp, 3, .production_id = 7),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eq_cmp, 3, .production_id = 7),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_literal, 4),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_literal, 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 2),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_neq_cmp, 3, .production_id = 7),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_neq_cmp, 3, .production_id = 7),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_access, 4, .production_id = 9),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_access, 4, .production_id = 9),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_or_expr, 3, .production_id = 7),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_or_expr, 3, .production_id = 7),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lth_cmp, 3, .production_id = 7),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lth_cmp, 3, .production_id = 7),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mod_expr, 3, .production_id = 7),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(101),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(89),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arguments, 3),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_divide, 3, .production_id = 7),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiply, 3, .production_id = 7),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substract, 3, .production_id = 7),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add, 3, .production_id = 7),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mth_cmp, 3, .production_id = 7),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mth_cmp, 3, .production_id = 7),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments_list, 1),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_initialization, 3, .production_id = 3),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [199] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(89),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_statement, 2),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_statement, 2),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_declaration, 2, .production_id = 1),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(17),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments_list, 2),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_initialization_statement, 2),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_initialization_statement, 2),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(63),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, .production_id = 8),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6, .production_id = 8),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_declaration, 4, .production_id = 5),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_initializer_list, 2),
  [276] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_initializer_list, 3, .production_id = 2),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 4),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_initialization, 1),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_constructor_initialization, 2, .production_id = 2),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_initialization, 3),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_list_initialization, 3),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_YAPL(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
